### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by nah0y** [olehxch/NetworkTool#1]
Hello there!

Really nice tool :)
It's not really an issue, more a question... sorry for asking here, I couldn't find anywhere else to contact you.

Calling "netsh wlan show networks" in a computer set in French, will display results... in French.
The question is, do you handle that? I mean, when we need to parse the result, you will have "Channel" for english and "Canal" for french...
Do you have a way to always display the result in English for example?

Thanks a lot!

**Comment by olehxch** [comment]
Hi
Thanks, really I hadn't thought that this app would be useful in the future

Generally this tool is not aware about system language, it just runs predefined commands to start/stop network. Currently it is adapted to English language. One idea is to change system language in the console and then run this commands, so output be in the right language, but I didn't tested it yet :)

p.s. added some contacts to my profile

**Comment by nah0y** [comment]
Hey! Thanks a lot for the fast answer ;)

Well, didn't find how to change the system language easily in the console, so I'll let that as it is :D
Have a great day ;)

**Comment by olehxch** [comment]
@nah0y but except language problems, is the application working?
maybe you can do some screenshots if text is not properly showing in the UI

**Comment by nah0y** [comment]
Well... I'm on a Mac and does have a PC Windows but without a wireless card...
I'm coding without testing for now =)
